camera/horizontal_fov: 74 #74 ## Horizontal field of view
camera/vertical_fov: 60 #60 ## Vertical field of view

camera/horizontal_fov_expanded: 90 ## Horizontal field of view
camera/vertical_fov_expanded: 90  ## Vertical field of view

raycast/dphi:  5  #5   ## Vertical angle step
raycast/dtheta: 5  #5   ## Horizontal angle step
raycast/r_max: 4.5   #5    ## Maximum radius to include calculation


octomap/topic_name: "/octomap_full" ## Octomap topic name published by octomap_server
octomap/save_path: "/home/fth/NBV_Youbot/src/map_" ## Path to save octomap
octomap/cell_size: 0.03  ## Resolution of the octomap
octomap/use_low_res: false ## Use low resolution octomap for focus point calculation
octomap/low_res_cell_size: 0.2  ## Resolution of the low resolution

focus_pnt/focus_r: 2.5  ## Radius to calculate the focus point.

frontier/neighbor_expansion: 2 ## Neighbor expansion radius for frontier visibility (0=off, 1=26 neighbors, 2=124 neighbors)

boundary/min: [-2.75, -2.75, 0.05]   ## Boundaries to include calculation
boundary/max: [2.75, 2.75, 4]






