<?xml version="1.0"?>
<package format="2">
  <name>orac_reconstruction_services</name>
  <version>0.0.0</version>
  <description>Service definitions for reconstruction and focus-point calculation.</description>

  <maintainer email="fatih.dursun@postgrad.manchester.ac.uk">Fatih Dursun</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>

</package>
